<template>
  <el-table
    class="table"
    style="width: 900px"
    :data="orderProductionData"
    border
  >
    <el-table-column
      prop="resource"
      label="资源"
      width="180"
      fixed
    />
    <el-table-column
      prop="time1"
      label="7点~8点"
      width="180"
    />
    <el-table-column
      prop="time2"
      label="8点~9点"
      width="180"
    />
    <el-table-column
      prop="time3"
      label="9点~10点"
      width="180"
    />
    <el-table-column
      prop="time4"
      label="10点~11点"
      width="180"
    />
    <el-table-column
      prop="time5"
      label="11点~12点"
      width="180"
    />
    <el-table-column
      prop="time6"
      label="12点~13点"
      width="180"
    />
    <el-table-column
      prop="time7"
      label="13点~14点"
      width="180"
    />
    <el-table-column
      prop="time8"
      label="14点~15点"
      width="180"
    />
    <el-table-column
      prop="time9"
      label="15点~16点"
      width="180"
    />
    <el-table-column
      prop="time10"
      label="16点~17点"
      width="180"
    />
    <el-table-column
      prop="time11"
      label="17点~18点"
      width="180"
    />
    <el-table-column
      prop="time12"
      label="18点~19点"
      width="180"
    />
    <el-table-column
      prop="time13"
      label="19点~20点"
      width="180"
    />
    <el-table-column
      prop="time14"
      label="20点~21点"
      width="180"
    />
    <el-table-column
      prop="time15"
      label="21点~22点"
      width="180"
    />
    <el-table-column
      prop="time16"
      label="22点~23点"
      width="180"
    />
    <el-table-column
      prop="time17"
      label="23点~24点"
      width="180"
    />
    <el-table-column
      prop="time18"
      label="24点~1点"
      width="180"
    />
    <el-table-column
      prop="time19"
      label="1点~2点"
      width="180"
    />
    <el-table-column
      prop="time20"
      label="2点~3点"
      width="180"
    />
    <el-table-column
      prop="time21"
      label="3点~4点"
      width="180"
    />
    <el-table-column
      prop="time22"
      label="4点~5点"
      width="180"
    />
    <el-table-column
      prop="time23"
      label="5点~6点"
      width="180"
    />
    <el-table-column
      prop="time24"
      label="6点~7点"
      width="180"
    />
  </el-table>
</template>

<script>
export default {
  name: 'GantTable',
  props:{
    orderProductionData:{
      default:()=>[
        {
          resource:'资源01',
          time1:'',
          time2:'订单1',
          time3:'订单1',
          time4:'',
          time5:'订单1',
          time6:'',
          time7:'订单1',
          time8:'订单1',
          time9:'',
          time10:'',
          time11:'订单1',
          time12:'订单1',
          time13:'',
          time14:'',
          time15:'',
          time16:'订单1',
          time17:'订单1',
          time18:'订单1',
          time19:'',
          time20:'订单1',
          time21:'订单1',
          time22:'',
          time23:'',
          time24:'订单1',

        },
        {
          resource:'资源02',
          time1:'',
          time2:'',
          time3:'',
          time4:'',
          time5:'订单1',
          time6:'',
          time7:'订单1',
          time8:'',
          time9:'',
          time10:'',
          time11:'订单1',
          time12:'订单1',
          time13:'',
          time14:'',
          time15:'',
          time16:'订单1',
          time17:'订单1',
          time18:'订单1',
          time19:'',
          time20:'订单1',
          time21:'订单1',
          time22:'',
          time23:'',
          time24:'订单1',
        },
      ]
    }
  }
}
</script>

<style scoped>

</style>
